apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vpro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpro-app
  template:
    metadata:
      labels:
        app: vpro-app
    spec:
      containers:
        - name: vprapp
          image: shady25/vproapp
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb; do echo waiting for the DB; sleep 2; done;",
            ]
        - name: init-cache
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprocache01; do echo waiting for the Cache; sleep 2; done;",
            ]
